Staj.AspNetMVC.StokTakip.Web/Models/Entities/Markalar.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Staj.AspNetMVC.StokTakip.Web.Models.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Markalar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Markalar()
        {
            this.Urunler = new HashSet<Urunler>();
        }

        public int Id { get; set; }

        [Required(ErrorMessage = "Kategori adı alanı boş geçilemez")]
        [Display(Name = "Kategori Adı")]
        public int KategoriId { get; set; }

        [Required(ErrorMessage = "Marka adı alanı boş geçilemez")]
        [Display(Name = "Marka Adı")]
        public string MarkaAdi { get; set; }

        [Required(ErrorMessage = "Açıklama alanı boş geçilemez")]
        [Display(Name = "Açıklama")]
        public string Aciklama { get; set; }

        public virtual Kategoriler Kategoriler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Urunler> Urunler { get; set; }
    }
}

Staj.AspNetMVC.StokTakip.Web/Models/Entities/Urunler.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Staj.AspNetMVC.StokTakip.Web.Models.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Urunler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Urunler()
        {
            this.Sepet = new HashSet<Sepet>();
            this.Satislar = new HashSet<Satislar>();
            this.MarkaListesi = new List<SelectListItem>();
            MarkaListesi.Insert(0, new SelectListItem { Text = "Önce kategori seçilmelidir", Value = "" });
        }

        public int Id { get; set; }

        [Required(ErrorMessage = "Kategori adı alanı boş geçilemez")]
        [Display(Name = "Kategori Adı")]
        public int KategoriId { get; set; }

        [Required(ErrorMessage = "Marka adı alanı boş geçilemez")]
        [Display(Name = "Marka Adı")]
        public int MarkaId { get; set; }

        [Required(ErrorMessage = "Ürün adı alanı boş geçilemez")]
        [Display(Name = "Ürün Adı")]
        public string UrunAdi { get; set; }

        [Required(ErrorMessage = "Barkod no alanı boş geçilemez")]
        [Display(Name = "Barkod No")]
        public string BarkodNo { get; set; }

        [Required(ErrorMessage = "Alış fiyatı alanı boş geçilemez")]
        [Display(Name = "Alış Fiyatı")]
        public decimal AlisFiyati { get; set; }

        [Required(ErrorMessage = "Satış fiyatı alanı boş geçilemez")]
        [Display(Name = "Satış Fiyatı")]
        public decimal SatisFiyati { get; set; }

        [Required(ErrorMessage = "Miktar alanı boş geçilemez")]
        [Display(Name = "Miktar")]
        public decimal? Miktari { get; set; }

        [Required(ErrorMessage = "KDV alanı boş geçilemez")]
        [Range(0, 100, ErrorMessage = "0-100 arası sayı girilmelidir")]
        public int KDV { get; set; }

        [Required(ErrorMessage = "Birim adı alanı boş geçilemez")]
        [Display(Name = "Birim Adı")]
        public int BirimId { get; set; }

        [DataType(DataType.Date)]
        [Required(ErrorMessage = "Tarih alanı boş geçilemez")]

        public System.DateTime Tarih { get; set; }

        [Required(ErrorMessage = "Açıklama alanı boş geçilemez")]
        [Display(Name = "Açıklama")]
        public string Aciklama { get; set; }

        public virtual Birimler Birimler { get; set; }
        public virtual Kategoriler Kategoriler { get; set; }
        public virtual Markalar Markalar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sepet> Sepet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Satislar> Satislar { get; set; }

        public List<SelectListItem> KategoriListesi { get; set; }
        public List<SelectListItem> MarkaListesi { get; set; }
        public List<SelectListItem> BirimListesi { get; set; }
    }
}

Staj.AspNetMVC.StokTakip.Web/Controllers/MarkalarController.cs
using Staj.AspNetMVC.StokTakip.Web.Models.Entities;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace Staj.AspNetMVC.StokTakip.Web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class MarkalarController : Controller
    {
        private readonly StokTakipDbEntities entity = new StokTakipDbEntities();
        public ActionResult Index()
        {
            var model = entity.Markalar.ToList();
            return View(model);
        }

        [HttpGet]
        public ActionResult MarkaEkle()
        {
            KategorileriGetir();
            return View();
        }

        private void KategorileriGetir()
        {
            List<SelectListItem> selectItems = new List<SelectListItem>(from x in entity.Kategoriler
                                                                        select new SelectListItem
                                                                        {
                                                                            Value = x.Id.ToString(),
                                                                            Text = x.KategoriAdi
                                                                        }).ToList();
            ViewBag.l = selectItems;
        }

        [HttpPost]
        public ActionResult MarkaEkle(Markalar marka)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.KategoriId = new SelectList(entity.Kategoriler, "Id", "KategoriAdi", marka.KategoriId);
                return View();
            }
            entity.Entry(marka).State = System.Data.Entity.EntityState.Added;
            entity.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult MarkaGuncellemeGetir(int id)
        {
            KategorileriGetir();
            var model = entity.Markalar.Find(id);
            return View(model);
        }

        public ActionResult MarkaGuncelle(Markalar marka)
        {
            if (!ModelState.IsValid)
            {
                KategorileriGetir();
                return View("MarkaGuncellemeGetir");
            }
            entity.Entry(marka).State = System.Data.Entity.EntityState.Modified;
            entity.SaveChanges();
            return RedirectToAction("Index");

        }

        public ActionResult MarkaSilmeGetir(int id)
        {
            var model = entity.Markalar.Find(id);
            if (model == null) return HttpNotFound();
            return View(model);
        }

        public ActionResult MarkaSil(Markalar marka)
        {
            entity.Entry(marka).State = System.Data.Entity.EntityState.Deleted;
            entity.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Urunler(int id)
        {
            var model = entity.Urunler.Where(I => I.Markalar.Id == id).ToList();
            var kategori = entity.Markalar.Where(I => I.Id == id).Select(I => I.Kategoriler.KategoriAdi).FirstOrDefault();
            var marka = entity.Markalar.Where(I => I.Id == id).Select(I => I.MarkaAdi).FirstOrDefault();
            ViewBag.k = kategori;
            ViewBag.m = marka;
            return View(model);
        }
    }
}

Staj.AspNetMVC.StokTakip.Web/Controllers/UrunlerController.cs
using Staj.AspNetMVC.StokTakip.Web.Models.Entities;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Web.Mvc;
using Excel = Microsoft.Office.Interop.Excel;

namespace Staj.AspNetMVC.StokTakip.Web.Controllers
{
    [Authorize]
    public class UrunlerController : Controller
    {
        private readonly StokTakipDbEntities entity = new StokTakipDbEntities();
        public ActionResult Index(string ara)
        {
            var model = entity.Urunler.ToList();
            if (!string.IsNullOrEmpty(ara))
            {
                model = model.Where(I => I.UrunAdi.ToLower().Contains(ara.ToLower()) || I.BarkodNo.ToLower().Contains(ara.ToLower())).ToList();
            }
            return View(model);
        }

        private void Yenile(Urunler model)
        {
            List<Kategoriler> kategoriList = entity.Kategoriler.OrderBy(I => I.KategoriAdi).ToList();
            model.KategoriListesi = (from x in kategoriList
                                     select new SelectListItem
                                     {
                                         Text = x.KategoriAdi,
                                         Value = x.Id.ToString()

                                     }).ToList();

            List<Birimler> birimList = entity.Birimler.OrderBy(I => I.BirimAdi).ToList();
            model.BirimListesi = (from x in birimList
                                  select new SelectListItem
                                  {
                                      Text = x.BirimAdi,
                                      Value = x.Id.ToString()
                                  }).ToList();
        }

        [HttpGet]
        public ActionResult UrunEkle()
        {
            var model = new Urunler();
            Yenile(model);
            return View(model);
        }

      

        [HttpPost]
        public ActionResult UrunEkle(Urunler urun)
        {
            if (!ModelState.IsValid)
            {
                var model = new Urunler();
                Yenile(model);
                return View(model);
            }
            entity.Entry(urun).State = System.Data.Entity.EntityState.Added;
            entity.SaveChanges();
            return RedirectToAction("Index");
        }

        public JsonResult MarkaGetir(int id)
        {
            var model = new Urunler();
            List<Markalar> markaListe = entity.Markalar.Where(I => I.KategoriId == id).OrderBy(I => I.MarkaAdi).ToList();
            model.MarkaListesi = (from x in markaListe
                                  select new SelectListItem
                                  {
                                      Text = x.MarkaAdi,
                                      Value = x.Id.ToString()
                                  }).ToList();
            model.MarkaListesi.Insert(0, new SelectListItem { Text = "Seçiniz", Value = "" });
            return Json(model.MarkaListesi, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult MiktarEkle(int id)
        {
            var model = entity.Urunler.Find(id);
            model.Miktari = null;
            return View(model);
        }

        [HttpPost]
        public ActionResult MiktarEkle(Urunler urun)
        {
            var model = entity.Urunler.Find(urun.Id);
            model.Miktari += urun.Miktari;
            if (model.Miktari == null)
            {
                ModelState.AddModelError("Miktari","Lütfen eklemek istediğiniz miktarı kutucuğa giriniz");
                return View(model);
            }
            entity.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult UrunGuncellemeGetir(int id)
        {
            var model = entity.Urunler.Find(id);
            Yenile(model);
            List<Markalar> markaList = entity.Markalar.Where(I => I.KategoriId == model.KategoriId).OrderBy(I => I.MarkaAdi).ToList();
            model.MarkaListesi = (from x in markaList
                                 select new SelectListItem
                                 {
                                     Text = x.MarkaAdi,
                                     Value = x.Id.ToString()
                                 }).ToList();
            return View(model);
        }

        [HttpPost]
        public ActionResult UrunGuncelle(Urunler u)
        {
            if (!ModelState.IsValid)
            {
                var model = entity.Urunler.Find(u.Id);
                Yenile(model);
                List<Markalar> markaList = entity.Markalar.Where(I => I.KategoriId == model.KategoriId).OrderBy(I => I.MarkaAdi).ToList();
                model.MarkaListesi = (from x in markaList
                                     select new SelectListItem
                                     {
                                         Text = x.MarkaAdi,
                                         Value = x.Id.ToString()
                                     }).ToList();
                return View(model);
            }

            entity.Entry(u).State = System.Data.Entity.EntityState.Modified;
            entity.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult UrunSilmeGetir(int id)
        {
            var model = entity.Urunler.Find(id);
            if (model == null) return HttpNotFound();
            return View(model);

        }
        public ActionResult UrunSil(Urunler urun)
        {
            entity.Entry(urun).State = System.Data.Entity.EntityState.Deleted;
            entity.SaveChanges();
            return RedirectToAction("Index");
        }

        public JsonResult ExcelDisaAktar()
        {
            try
            {
                var liste = entity.Urunler.ToList();
                Excel.Application application = new Excel.Application();
                Excel.Workbook workbook = application.Workbooks.Add(System.Reflection.Missing.Value);
                Excel.Worksheet worksheet = workbook.ActiveSheet;
                worksheet.Cells[1, 1] = "Id";
                worksheet.Cells[1, 2] = "Ürün Adı";
                worksheet.Cells[1, 3] = "Barkod No";
                worksheet.Cells[1, 4] = "Fiyatı";
                worksheet.Cells[1, 5] = "Miktarı";
                worksheet.Cells[1, 6] = "Tarih";

                int row = 2;
                foreach (var item in liste)
                {
                    worksheet.Cells[row, 1] = item.Id;
                    worksheet.Cells[row, 2] = item.UrunAdi;
                    worksheet.Cells[row, 3] = item.BarkodNo;
                    worksheet.Cells[row, 4] = item.SatisFiyati;
                    worksheet.Cells[row, 5] = item.Miktari;
                    worksheet.Cells[row, 6] = item.Tarih;

                    worksheet.Cells[row, 2].ColumnWidth = 15;
                    worksheet.Cells[row, 4].ColumnWidth = 15;
                    worksheet.Cells[row, 6].ColumnWidth = 15;
                    row++;
                }
                var heading = worksheet.get_Range("A1", "F1");
                heading.Font.Bold = true;
                heading.Font.Size = 13;
                heading.Font.Color = Color.Blue;

                var range_Fiyat = worksheet.get_Range("D2", "D" + row);
                range_Fiyat.NumberFormat = "#,###,###.00";

                var range_Tarih = worksheet.get_Range("F2", "F" + row);
                range_Tarih.NumberFormat = "dd.MM.yyyy";

                workbook.SaveAs(Environment.GetFolderPath(Environment.SpecialFolder.Desktop) + "\\Ürün Listesi - " + Guid.NewGuid() + ".xlsx");
                workbook.Close();
                application.Quit();


                ViewBag.Mesaj = "İşlem başarılı. Dosya masaüstüne konumlandırıldı.";
            }
            catch (Exception)
            {
                ViewBag.Mesaj = "İşlem başarısız. Bir hata meydana geldi.";
            }
            return Json(ViewBag.Mesaj, JsonRequestBehavior.AllowGet);
        }

    }
}

Staj.AspNetMVC.StokTakip.Web/Views/Markalar/Index.cshtml
@model List<Staj.AspNetMVC.StokTakip.Web.Models.Entities.Markalar>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="bg-dark my-5 mx-auto">
    <div class="card shadow-lg mt-2" style="border:0">
        <div class="card-header bg-dark">
            <h2 style="color:#e9d362;">Marka Listesi</h2>
        </div>
        <div class="card-body bg-dark">

            <table class="table table-bordered table-hover table-dark table-responsive">
                <thead class="text-center text-white">
                    <tr>
                        <th>Id</th>
                        <th>Kategori</th>
                        <th>Marka</th>
                        <th>Açıklama</th>
                        <th colspan="3">İşlemler</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Id</td>
                            <td>@item.Kategoriler.KategoriAdi</td>
                            <td>@item.MarkaAdi</td>
                            <td>@item.Aciklama</td>
                            <td>
                                <a href="/Markalar/MarkaSilmeGetir/@item.Id" class="btn btn-outline-danger">Sil</a>
                            </td>
                            <td>
                                <a href="/Markalar/MarkaGuncellemeGetir/@item.Id" class="btn btn-outline-warning">Güncelle</a>
                            </td>
                            <td>
                                <a href="/Markalar/Urunler/@item.Id" class="btn btn-outline-info">Ürünler</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>

            <a href="/Markalar/MarkaEkle" class="btn btn-outline-primary">Marka Ekle</a>

        </div>
    </div>
</div>

Staj.AspNetMVC.StokTakip.Web/Views/Markalar/MarkaEkle.cshtml
@model Staj.AspNetMVC.StokTakip.Web.Models.Entities.Markalar
@{
    ViewBag.Title = "MarkaEkle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="bg-dark w-50 my-5 mx-auto">
    <div class="card shadow-lg mt-3" style="border:0">
        <div class="card-header bg-dark">
            <h2 style="color:#e9d362;">Marka Ekle</h2>
        </div>
        <div class="card-body bg-dark text-info">
            @using (Html.BeginForm("MarkaEkle", "Markalar", FormMethod.Post))
            {
                <div class="form-group">
                    @Html.LabelFor(I => I.Kategoriler.KategoriAdi)


                    @Html.DropDownListFor(I => I.KategoriId, (List<SelectListItem>)ViewBag.l, "---Seçiniz---", new { @class = "form-control" })

                    @*@Html.DropDownList("KategoriId", (List<SelectListItem>)ViewBag.l, "---Seçiniz---", new { @class = "form-control" })*@

                    @*@Html.DropDownList("KategoriId", null, "---Seçiniz---", new { @class = "form-control" })*@

                    @Html.ValidationMessageFor(I => I.KategoriId, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(I => I.MarkaAdi)
                    @Html.TextBoxFor(I => I.MarkaAdi, new { @class = "form-control" })
                    @Html.ValidationMessageFor(I => I.MarkaAdi, "", new { @class = "text-danger" })

                </div>
                <div class="form-group">
                    @Html.LabelFor(I => I.Aciklama)
                    @Html.TextBoxFor(I => I.Aciklama, new { @class = "form-control" })
                    @Html.ValidationMessageFor(I => I.Aciklama, "", new { @class = "text-danger" })

                </div>
                <div class="form-group">
                    <button class="btn btn-success">Kaydet</button>
                    <a class="btn btn-danger float-right" href="/Markalar/Index/">İptal</a>
                </div>
            }
        </div>
    </div>
</div>


@section scriptdanger{
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
}

Staj.AspNetMVC.StokTakip.Web/Views/Markalar/MarkaGuncellemeGetir.cshtml
@model Staj.AspNetMVC.StokTakip.Web.Models.Entities.Markalar
@{
    ViewBag.Title = "MarkaGuncellemeGetir";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="bg-dark w-50 my-5 mx-auto">
    <div class="card shadow-lg mt-3" style="border:0">
        <div class="card-header bg-dark">
            <h2 style="color: #e9d362;">Marka Güncelle</h2>
        </div>
        <div class="card-body bg-dark text-info" style="color: #e9d362;">
            @using (Html.BeginForm("MarkaGuncelle", "Markalar"))
            {
                @Html.HiddenFor(I => I.Id)
                <div class="form-group">
                    @Html.LabelFor(I => I.Kategoriler.KategoriAdi)
                    @Html.DropDownListFor(I => I.KategoriId, (List<SelectListItem>)ViewBag.l, "---Seçiniz---", new { @class = "form-control" })
                    @Html.ValidationMessageFor(I => I.KategoriId, null, new { @class = "text-danger" })

                </div>
                <div class="form-group">
                    @Html.LabelFor(I => I.MarkaAdi)
                    @Html.TextBoxFor(I => I.MarkaAdi, new { @class = "form-control" })
                    @Html.ValidationMessageFor(I => I.MarkaAdi, null, new { @class = "text-danger" })

                </div>

                <div class="form-group">
                    @Html.LabelFor(I => I.Aciklama)
                    @Html.TextBoxFor(I => I.Aciklama, new { @class = "form-control" })
                    @Html.ValidationMessageFor(I => I.Aciklama, null, new { @class = "text-danger" })

                </div>
                <div class="form-group">
                    <button class="btn btn-success">Kaydet</button>
                    <a class="btn btn-danger float-right" href="/Markalar/Index/">İptal</a>
                </div>
            }

        </div>
    </div>
</div>

@section scriptdanger{
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
}

Staj.AspNetMVC.StokTakip.Web/Views/Markalar/MarkaSilmeGetir.cshtml
@model Staj.AspNetMVC.StokTakip.Web.Models.Entities.Markalar
@{
    ViewBag.Title = "MarkaSilmeGetir";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="bg-dark w-25 my-5 mx-auto">
    <div class="card shadow-lg mt-3" style="border:0">
        <div class="card-header bg-dark">
            <h2 style="color:#e9d362;">Marka Sil</h2>
        </div>
        <div class="card-body bg-dark text-info">
            @using (Html.BeginForm("MarkaSil", "Markalar"))
            {
                @Html.HiddenFor(I => I.Id)
                <div class="form-group">
                    @Html.LabelFor(I => I.Kategoriler.KategoriAdi):
                    <span class="text-light">@Html.DisplayFor(I => I.Kategoriler.KategoriAdi)</span>
                </div>
                <div class="form-group">
                    @Html.LabelFor(I => I.MarkaAdi):
                    <span class="text-light">@Html.DisplayFor(I => I.MarkaAdi)</span>
                </div>
                <div class="form-group">
                    @Html.LabelFor(I => I.Aciklama):
                    <span class="text-light">@Html.DisplayFor(I => I.Aciklama)</span>
                </div>

                <h5 class="text-primary mt-5 mb-4">Kayıt silinsin mi?</h5>
                <div class="form-group">
                    <button class="btn btn-danger">Sil</button><a class="btn btn-secondary float-right" href="/Markalar/Index/">İptal</a>
                </div>
            }

        </div>
    </div>
</div>

Staj.AspNetMVC.StokTakip.Web/Views/Markalar/Urunler.cshtml
@model List<Staj.AspNetMVC.StokTakip.Web.Models.Entities.Urunler>
@{
    ViewBag.Title = "Urunler";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="bg-dark my-5 mx-auto w-75">
    <div class="card shadow-lg mt-2" style="border:0">
        <div class="card-header bg-dark">
            <h2 style="color:#e9d362;">@ViewBag.k - @ViewBag.m Grubundaki Ürünler</h2>
        </div>
        <div class="card-body bg-dark">
            <table class="table table-bordered table-hover table-dark">
                <thead class="text-center text-white">
                    <tr class="text-center text-white">
                        <th>Id</th>
                        <th>Ürün Adı</th>
                        <th>Barkod No</th>
                        <th>Alış Fiyatı</th>
                        <th>Fiyatı</th>
                        <th>Miktarı</th>
                        <th>Birim</th>
                        <th>KDV</th>
                        <th>Tarih</th>
                        <th>Açıklama</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@Html.DisplayFor(I => item.Id) </td>
                            <td>@Html.DisplayFor(I => item.UrunAdi) </td>
                            <td>@Html.DisplayFor(I => item.BarkodNo) </td>
                            <td>@Html.DisplayFor(I => item.AlisFiyati) TL</td>
                            <td>@Html.DisplayFor(I => item.SatisFiyati) TL</td>
                            <td>@Html.DisplayFor(I => item.Miktari)</td>
                            <td>@Html.DisplayFor(I => item.Birimler.BirimAdi) </td>
                            <td>% @Html.DisplayFor(I => item.KDV) </td>
                            <td>@Html.DisplayFor(I => item.Tarih) </td>
                            <td>@Html.DisplayFor(I => item.Aciklama)</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>