Staj.AspNetMVC.StokTakip.Web/Models/Entities/Birimler.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Staj.AspNetMVC.StokTakip.Web.Models.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Birimler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Birimler()
        {
            this.Urunler = new HashSet<Urunler>();
        }

        public int Id { get; set; }

        [Required(ErrorMessage = "Birim adı alanı boş geçilemez")]
        [Display(Name = "Birim Adı")]
        public string BirimAdi { get; set; }

        [Required(ErrorMessage = "Açıklama alanı boş geçilemez")]
        [Display(Name = "Açıklama")]
        public string Aciklama { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Urunler> Urunler { get; set; }
    }
}

Staj.AspNetMVC.StokTakip.Web/Controllers/BirimlerController.cs
using Staj.AspNetMVC.StokTakip.Web.Models.Entities;
using System.Linq;
using System.Web.Mvc;

namespace Staj.AspNetMVC.StokTakip.Web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class BirimlerController : Controller
    {
        private readonly StokTakipDbEntities entity = new StokTakipDbEntities();

        public ActionResult Index()
        {
            return View(entity.Birimler.ToList());
        }

        [HttpGet]
        public ActionResult BirimEkle()
        {
            return View();
        }

        [HttpPost]
        public ActionResult BirimEkle(Birimler birim)
        {
            if (!ModelState.IsValid) return View("BirimEkle");
            entity.Birimler.Add(birim);
            entity.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult BirimGuncellemeGetir(int id)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            var model = entity.Birimler.Find(id);
            if (model == null) return HttpNotFound();
            return View(model);
        }

        public ActionResult BirimGuncelle(Birimler birim)
        {
            entity.Entry(birim).State = System.Data.Entity.EntityState.Modified;
            entity.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult BirimSilmeGetir(int id)
        {
            var model = entity.Birimler.Find(id);
            if (model == null) return HttpNotFound();
            return View(model);
        }

        public ActionResult BirimSil(Birimler birim)
        {
            entity.Entry(birim).State = System.Data.Entity.EntityState.Deleted;
            entity.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Staj.AspNetMVC.StokTakip.Web/Views/Birimler/BirimEkle.cshtml
@model Staj.AspNetMVC.StokTakip.Web.Models.Entities.Birimler
@{
    ViewBag.Title = "BirimEkle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="bg-dark w-50 my-5 mx-auto">
    <div class="card shadow-lg mt-3" style="border:0">
        <div class="card-header bg-dark">
            <h2 style="color:#e9d362;">Birim Ekle</h2>
        </div>
        <div class="card-body bg-dark text-info">

            @using (Html.BeginForm("BirimEkle", "Birimler", FormMethod.Post))
            {
                <div class="form-group">
                    @Html.LabelFor(I => I.BirimAdi)
                    @Html.TextBoxFor(I => I.BirimAdi, new { @class = "form-control" })
                    @Html.ValidationMessageFor(I => I.BirimAdi, null, new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(I => I.Aciklama)
                    @Html.TextAreaFor(I => I.Aciklama, new { @class = "form-control" })
                    @Html.ValidationMessageFor(I => I.Aciklama, null, new { @class = "text-danger" })
                </div>
                <div>
                    <button class="btn btn-success">Kaydet</button>
                    <a class="btn btn-danger float-right" href="/Birimler/Index/">İptal</a>

                </div>
            }
        </div>
    </div>
</div>

@section scriptdanger{
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
}

Staj.AspNetMVC.StokTakip.Web/Views/Birimler/BirimGuncellemeGetir.cshtml
@model Staj.AspNetMVC.StokTakip.Web.Models.Entities.Birimler
@{
    ViewBag.Title = "BirimGuncellemeGetir";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="bg-dark w-50 my-5 mx-auto">
    <div class="card shadow-lg mt-3" style="border:0">
        <div class="card-header bg-dark">
            <h2 style="color: #e9d362;">Birim Güncelle</h2>
        </div>
        <div class="card-body bg-dark text-info" style="color: #e9d362;">
            @using (Html.BeginForm("BirimGuncelle", "Birimler", FormMethod.Post))
            {
                <div class="form-group">
                    @Html.HiddenFor(I => I.Id)
                    @Html.LabelFor(I => I.BirimAdi)
                    @Html.TextBoxFor(I => I.BirimAdi, new { @class = "form-control" })
                    @Html.ValidationMessageFor(I => I.BirimAdi, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(I => I.Aciklama)
                    @Html.TextAreaFor(I => I.Aciklama, new { @class = "form-control" })
                    @Html.ValidationMessageFor(I => I.Aciklama, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    <button class="btn btn-success">Kaydet</button>
                    <a class="btn btn-danger float-right" href="/Birimler/Index/">İptal</a>
                </div>
            }
        </div>
    </div>
</div>

@section scriptdanger{
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
}

Staj.AspNetMVC.StokTakip.Web/Views/Birimler/BirimSilmeGetir.cshtml
@model Staj.AspNetMVC.StokTakip.Web.Models.Entities.Birimler
@{
    ViewBag.Title = "BirimSilmeGetir";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="bg-dark w-25 my-5 mx-auto">
    <div class="card shadow-lg mt-3" style="border:0">
        <div class="card-header bg-dark">
            <h2 style="color:#e9d362;">Birim Sil</h2>
        </div>
        <div class="card-body bg-dark text-info">

            @using (Html.BeginForm("BirimSil", "Birimler"))
            {
                <div>
                    @Html.HiddenFor(I => I.Id)
                    @Html.LabelFor(I => I.BirimAdi):
                    <span class="text-light">@Html.DisplayFor(I => I.BirimAdi, new { @class = "form-control" })</span>
                </div>
                <div>
                    @Html.LabelFor(I => I.Aciklama):
                    <span class="text-light">@Html.DisplayFor(I => I.Aciklama, new { @class = "form-control" })</span>
                </div>
                <h5 class="text-primary mt-5 mb-4">Kayıt silinsin mi?</h5>

                <div class="form-group">
                    <button class="btn btn-danger">Sil</button> <a class="btn btn-secondary float-right" href="/Birimler/Index/">İptal</a>
                </div>
            }
        </div>
    </div>
</div>

Staj.AspNetMVC.StokTakip.Web/Views/Birimler/Index.cshtml
@model List<Staj.AspNetMVC.StokTakip.Web.Models.Entities.Birimler>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="bg-dark my-5 mx-auto">
    <div class="card shadow-lg mt-2" style="border:0">
        <div class="card-header bg-dark">
            <h2 style="color:#e9d362;">Birim Listesi</h2>
        </div>
        <div class="card-body bg-dark">
            <table class="table table-bordered table-hover table-dark table-responsive">
                <thead class="text-center text-white">
                    <tr>
                        <th>Id</th>
                        <th>Birim Adı</th>
                        <th>Açıklama</th>
                        <th colspan="2">İşlemler</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Id</td>
                            <td>@item.BirimAdi</td>
                            <td>@item.Aciklama</td>
                            <td>
                                <a href="/Birimler/BirimSilmeGetir/@item.Id" class="btn btn-outline-danger">Sil</a>
                            </td>
                            <td>
                                <a href="/Birimler/BirimGuncellemeGetir/@item.Id" class="btn btn-outline-warning">Güncelle</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>

            <a href="/Birimler/BirimEkle/" class="btn btn-outline-primary mt-1 float-left">Birim Ekle</a>


        </div>
    </div>
</div>