Staj.AspNetMVC.StokTakip.Web/Models/Entities/Sepet.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Staj.AspNetMVC.StokTakip.Web.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sepet
    {
        public int Id { get; set; }
        public int KullaniciId { get; set; }
        public int UrunId { get; set; }
        public decimal BirimFiyati { get; set; }
        public decimal Miktari { get; set; }
        public decimal ToplamFiyati { get; set; }
        public System.DateTime Tarih { get; set; }
        public System.DateTime Saat { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual Urunler Urunler { get; set; }
    }
}

Staj.AspNetMVC.StokTakip.Web/Controllers/SatislarController.cs
using Staj.AspNetMVC.StokTakip.Web.Models.Entities;
using System;
using System.Linq;
using System.Web.Mvc;

namespace Staj.AspNetMVC.StokTakip.Web.Controllers
{
    [Authorize]
    public class SatislarController : Controller
    {
        private readonly StokTakipDbEntities entity = new StokTakipDbEntities();
        public ActionResult Index()
        {
            var model = entity.Satislar.ToList();
            return View(model);
        }

        public ActionResult SatinAl(int id)
        {
            var model = entity.Sepet.FirstOrDefault(I => I.Id == id);
            return View(model);
        }

        [HttpPost]
        public ActionResult SatinAlPost(int id)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var model = entity.Sepet.FirstOrDefault(I => I.Id == id);
                    var urun = entity.Urunler.FirstOrDefault(I => I.Id == model.UrunId);
                    urun.Miktari -= model.Miktari;
                    var satis = new Satislar
                    {
                        KullaniciId = model.KullaniciId,
                        UrunId = model.UrunId,
                        SepetId = model.Id,
                        BarkodNo = model.Urunler.BarkodNo,
                        BirimFiyati = model.BirimFiyati,
                        Miktari = model.Miktari,
                        ToplamFiyati = model.ToplamFiyati,
                        KDV = model.Urunler.KDV,
                        BirimId = model.Urunler.BirimId,
                        Tarih = DateTime.Now,
                        Saat = DateTime.Now
                    };
                    entity.Sepet.Remove(model);
                    entity.Satislar.Add(satis);
                    entity.SaveChanges();
                    ViewBag.Islem = "Satın alma işlemi başarılı...";
                }
            }
            catch (Exception)
            {
                ViewBag.Islem = "Satın alma esnasında bir hata meydana geldi !";
            }
            return View("Islem");
        }

        public ActionResult TamaminiSatinAl(decimal? tutar)
        {
            if (User.Identity.IsAuthenticated)
            {
                var kullaniciAdi = User.Identity.Name;
                var kullanici = entity.Kullanicilar.FirstOrDefault(I => I.KullaniciAdi == kullaniciAdi);
                var model = entity.Sepet.Where(I => I.KullaniciId == kullanici.Id).ToList();
                var kullaniciSepet = entity.Sepet.FirstOrDefault(I => I.KullaniciId == kullanici.Id);
                if (model != null)
                {
                    if (kullaniciSepet == null)
                    {
                        ViewBag.Tutar = "Sepetinizde ürün bulunmuyor";
                    }
                    else if (kullaniciSepet != null)
                    {
                        tutar = entity.Sepet.Where(I => I.KullaniciId == kullaniciSepet.KullaniciId).Sum(I => I.ToplamFiyati);
                        ViewBag.Tutar = "Toplam Tutar: " + tutar + " TL";
                    }
                    return View(model);
                }
            }
            return HttpNotFound();
        }

        [HttpPost]
        public ActionResult TamaminiSatinAlPost()
        {
            var userName = User.Identity.Name;
            var kullanici = entity.Kullanicilar.FirstOrDefault(I => I.KullaniciAdi == userName);
            var model = entity.Sepet.Where(I => I.KullaniciId == kullanici.Id).ToList();
            int satir = 0;
            try
            {
                foreach (var item in model)
                {
                    var satis = new Satislar
                    {
                        KullaniciId = model[satir].KullaniciId,
                        UrunId = model[satir].UrunId,
                        SepetId = model[satir].Id,
                        BarkodNo = model[satir].Urunler.BarkodNo,
                        BirimFiyati = model[satir].BirimFiyati,
                        Miktari = model[satir].Miktari,
                        ToplamFiyati = model[satir].ToplamFiyati,
                        KDV = model[satir].Urunler.KDV,
                        BirimId = model[satir].Urunler.BirimId,
                        Tarih = DateTime.Now,
                        Saat = DateTime.Now
                    };
                    entity.Satislar.Add(satis);
                    satir++;
                }
                foreach (var item in model)
                {
                    var urun = entity.Urunler.FirstOrDefault(I => I.Id == item.UrunId);
                    if (urun != null)
                    {
                        urun.Miktari -= item.Miktari;
                    }
                }
                ViewBag.Islem = "Satın alma işlemi başarılı...";
                entity.Sepet.RemoveRange(model);
                entity.SaveChanges();
            }
            catch (Exception)
            {
                ViewBag.Islem = "Satın alma esnasında bir hata meydana geldi !";
            }
            return View("Islem");
        }

    }
}

Staj.AspNetMVC.StokTakip.Web/Controllers/SepetController.cs
using Staj.AspNetMVC.StokTakip.Web.Models.Entities;
using System;
using System.Linq;
using System.Web.Mvc;

namespace Staj.AspNetMVC.StokTakip.Web.Controllers
{
    [Authorize]
    public class SepetController : Controller
    {
        private readonly StokTakipDbEntities entity = new StokTakipDbEntities();
        public ActionResult Index(decimal? tutar)
        {
            if (User.Identity.IsAuthenticated)
            {
                var kullaniciAdi = User.Identity.Name;
                var kullanici = entity.Kullanicilar.FirstOrDefault(I => I.KullaniciAdi == kullaniciAdi);
                var model = entity.Sepet.Where(I => I.KullaniciId == kullanici.Id).ToList();
                var kid = entity.Sepet.FirstOrDefault(I => I.KullaniciId == kullanici.Id);
                if (model != null)
                {
                    if (kid == null)
                    {
                        ViewBag.Tutar = "Sepetinizde ürün bulunmuyor";
                    }
                    else if (kid != null)
                    {
                        tutar = entity.Sepet.Where(I => I.KullaniciId == kid.KullaniciId).Sum(I => I.ToplamFiyati);
                        ViewBag.Tutar = "Toplam Tutar: " + tutar + " TL";
                    }
                    return View(model);

                }
            }
            return HttpNotFound();
        }

        public ActionResult SepeteEkle(int id)
        {
            if (User.Identity.IsAuthenticated)
            {
                var kullaniciAdi = User.Identity.Name;
                var model = entity.Kullanicilar.FirstOrDefault(I => I.KullaniciAdi == kullaniciAdi);
                var u = entity.Urunler.Find(id);
                var sepet = entity.Sepet.FirstOrDefault(I => I.KullaniciId == model.Id && I.UrunId == id);
                if (model != null)
                {
                    if (sepet != null)
                    {
                        sepet.Miktari++;
                        sepet.ToplamFiyati = u.SatisFiyati * sepet.Miktari;
                        entity.SaveChanges();
                        return RedirectToAction("Index", "Urunler");
                    }

                    var s = new Sepet
                    {
                        KullaniciId = model.Id,
                        UrunId = u.Id,
                        Miktari = 1,
                        BirimFiyati = u.SatisFiyati,
                        ToplamFiyati = u.SatisFiyati,
                        Tarih = DateTime.Now,
                        Saat = DateTime.Now
                    };
                    entity.Entry(s).State = System.Data.Entity.EntityState.Added;
                    entity.SaveChanges();
                    return RedirectToAction("Index", "Urunler");
                }
            }
            return HttpNotFound();
        }


        public ActionResult ToplamUrunSayisi(int? toplam)
        {
            if (User.Identity.IsAuthenticated)
            {
                var model = entity.Kullanicilar.FirstOrDefault(I => I.KullaniciAdi == User.Identity.Name);
                toplam = entity.Sepet.Where(I => I.KullaniciId == model.Id).Count();
                ViewBag.Count = toplam;
                if (toplam == 0)
                {
                    ViewBag.Count = "";
                }
                return PartialView();
            }
            return HttpNotFound();
        }

        public ActionResult Arttir(int id)
        {
            var model = entity.Sepet.Find(id);
            model.Miktari++;
            model.ToplamFiyati = model.BirimFiyati * model.Miktari;
            entity.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Azalt(int id)
        {
            var model = entity.Sepet.Find(id);
            if (model.Miktari == 1)
            {
                entity.Sepet.Remove(model);
                entity.SaveChanges();
            }
            model.Miktari--;
            model.ToplamFiyati = model.BirimFiyati * model.Miktari;
            entity.SaveChanges();
            return RedirectToAction("Index");
        }

        public void DinamikMiktar(int id, decimal miktari)
        {
            var model = entity.Sepet.Find(id);
            model.Miktari = miktari;
            model.ToplamFiyati = model.BirimFiyati * model.Miktari;
            entity.SaveChanges();
        }

        public ActionResult SepetSil(int id)
        {
            var model = entity.Sepet.Find(id);
            entity.Sepet.Remove(model);
            entity.SaveChanges();
            return RedirectToAction("Index");
        }


        public ActionResult SepetTamaminiSil()
        {
            if (User.Identity.IsAuthenticated)
            {
                var kullaniciAdi = User.Identity.Name;
                var model = entity.Kullanicilar.FirstOrDefault(I => I.KullaniciAdi.Equals(kullaniciAdi));
                var silinecekler = entity.Sepet.Where(I => I.KullaniciId.Equals(model.Id));
                entity.Sepet.RemoveRange(silinecekler);
                entity.SaveChanges();
                return RedirectToAction("Index");
            }
            return HttpNotFound();
        }
    }
}

Staj.AspNetMVC.StokTakip.Web/Views/Sepet/Index.cshtml
@model List<Staj.AspNetMVC.StokTakip.Web.Models.Entities.Sepet>
@using Staj.AspNetMVC.StokTakip.Web.Models.Entities
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    .azalt {
        display: block;
        cursor: pointer;
        border: solid 1px #ccc;
        position: absolute;
    }

    .txt {
        line-height: 18px;
        width: 50px !important;
        height: 32px;
        font-size: 14px;
        text-align: center;
        border: solid 1px #ccc;
        margin-right: 17px;
        margin-left: 22px;
    }

    .arttir {
        display: block;
        cursor: pointer;
        border: solid 1px #ccc;
        position: absolute;
        width: 25px;
        margin-top: -32px;
        margin-left: 71px;
    }
</style>


<div class="bg-dark my-5 mx-auto">
    <div class="card shadow-lg mt-2" style="border:0">
        <div class="card-header bg-dark">
            <h2 style="color:#e9d362;">Sepetim</h2>
        </div>
        <div class="card-body bg-dark">

            <table class="table table-bordered table-hover table-dark table-responsive">
                <thead class="text-center text-white">
                    <tr>
                        <th>Ürün Bilgisi</th>
                        <th>Birim Fiyatı</th>
                        <th>Miktarı</th>
                        <th>Toplam Fiyatı</th>
                        <th>Tarih</th>
                        <th>Saat</th>
                        <th colspan="2">İşlemler</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Urunler.Kategoriler.KategoriAdi - @item.Urunler.Markalar.MarkaAdi - @item.Urunler.BarkodNo - @item.Urunler.UrunAdi</td>
                            <td>@item.BirimFiyati TL</td>
                            <td>
                                <div class="mr-2">
                                    <div>
                                        @Html.ActionLink("-", "Azalt", new { id = item.Id }, new { @class = "font-weight-bold btn btn-sm btn-info azalt" })
                                    </div>
                                    @Html.TextBoxFor(I => item.Miktari, new { @class = "txt", @style = "background-color:#cccccc !important;", data_id = item.Id })
                                    <div>
                                        @Html.ActionLink("+", "Arttir", new { id = item.Id }, new { @class = "font-weight-bold btn btn-sm btn-info arttir" })
                                    </div>
                                </div>
                            </td>
                            @*<td>@item.Miktari @item.Urunler.Birimler.BirimAdi</td>*@
                            <td>@item.ToplamFiyati TL</td>
                            <td>@item.Tarih.ToString("dd.MM.yyyy")</td>
                            <td>@item.Saat.ToString("HH:mm")</td>
                            <td>@Html.ActionLink("Sil", "SepetSil", new { id = item.Id }, new { @class = "btn btn-outline-danger" })</td>
                            <td>@Html.ActionLink("Satın Al", "SatinAl", "Satislar", new { id = item.Id }, new { @class = "btn btn-outline-success" })</td>
                        </tr>

                    }
                </tbody>
            </table>
            <div class="font-weight-bold text-primary mb-5">@ViewBag.Tutar</div>

            @*<div class="container mt-2 mb-5">
                    @ViewBag.Tutar
                </div>*@

            <div class="container form-group">

                @Html.ActionLink("Tamamını Sil", "SepetTamaminiSil", "Sepet", null, new { @class = "btn btn-danger", @style="width:49%"})
                @Html.ActionLink("Tamamını Satın Al", "TamaminiSatinAl", "Satislar", null, new { @class = "btn btn-success", @style = "width:49%" })

            </div>


        </div>

    </div>
</div>



<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script>
    $(function () {
        $('.txt').on('change', function () {
            var miktar = $(this).val();
            var sepetid = $(this).attr('data-id');
            $.ajax({
                url: '/Sepet/DinamikMiktar/',
                data: { id: sepetid, miktari: miktar },
                success: function (res) {
                    document.location.reload();
                }
            });
        });
    });
</script>

Staj.AspNetMVC.StokTakip.Web/Views/Sepet/ToplamUrunSayisi.cshtml
@ViewBag.Count